'use strict';
const $=id=>document.getElementById(id), nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}), pct=v=>new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1}).format(v||0);
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const blank=v=>v===null||v===undefined||v===''; const valueLabel=v=>blank(v)?'Não informado':String(v);
const dateLabel=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v))?v.slice(8,10)+'/'+v.slice(5,7)+'/'+v.slice(0,4):String(v??'—');
const display=(v,h)=>blank(v)?'—':['Prazo DELI','PrimDataProg'].includes(h)?dateLabel(v):h==='qtdPlanUPS'?nf.format(v):String(v);
const addDays=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const mappings={fPolo:'Polo',fCompany:'Empreiteira_Contratos',fOwner:'Dono',fProg:'SttProg',fFamily:'Família',fArea:'Area',fLayer:'camada',fStatus:'Stt Proj',fKpi:'KPI Nota',fCode:'CÓDTEC',fCircuit:'Circuito'};
const labels={'definicao_do_projeto':'Projeto','nota':'Nota','Stt Proj':'Status do projeto','KPI Nota':'KPI da nota','Empreiteira_Contratos':'Empreiteira','qtdPlanUPS':'UPS planejadas','Area':'Área','camada':'Camada','SttProg':'Programação','PrimDataProg':'Data de programação','Dono':'Técnico / dono','CÓDTEC':'Código técnico'};
let data=structuredClone(window.DONO_DATA),records=[],filtered=[],page=1,sortKey='',sortDir=1,sheetPage=1,activeTab='overview';
function notice(text,error=false){$('notice').textContent=text;$('notice').hidden=false;$('notice').classList.toggle('error',error)}
function initialize(){records=data.rows.map((row,index)=>({...Object.fromEntries(data.headers.map((h,i)=>[h,row[i]??null])),_index:index}));
 for(const[id,key]of Object.entries(mappings)){const values=[...new Set(records.map(r=>blank(r[key])?'__blank__':String(r[key])))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true}));$(id).innerHTML='<option value="">Todos</option>'+values.map(v=>`<option value="${escapeHTML(v)}">${escapeHTML(v==='__blank__'?'Não informado':v)}</option>`).join('')}
 $('source').textContent=`${data.source} · Base: ${dateLabel(data.updated)} · ${nf.format(records.length)} registros`;
 $('reference').value=data.reference||'2026-09-21';$('sheetSelect').innerHTML=data.sheets.map((s,i)=>`<option value="${i}">${escapeHTML(s.name)}</option>`).join('');sheetPage=1;clearFilters();renderSheets();renderAuditSource();}
function deadline(r){const d=r['Prazo DELI'],ref=$('reference').value||data.reference;if(!d)return'missing';if(d<ref)return'overdue';return d<=addDays(ref,15)?'soon':'future'}
function clearFilters(){for(const id of [...Object.keys(mappings),'search','fDeadline','from','to'])$(id).value='';page=1;render()}
function filterRows(){const q=norm($('search').value),from=$('from').value,to=$('to').value,df=$('dateField').value;
 return records.filter(r=>Object.entries(mappings).every(([id,h])=>!$(id).value||($(id).value==='__blank__'?blank(r[h]):String(r[h])===$(id).value))&&(!q||data.headers.some(h=>norm(display(r[h],h)).includes(q)))&&(!$('fDeadline').value||deadline(r)===$('fDeadline').value)&&(!from||(r[df]&&r[df]>=from))&&(!to||(r[df]&&r[df]<=to)))}
function setFilter(id,value){$(id).value=blank(value)?'__blank__':String(value);page=1;render()}
function group(rs,key){const m=new Map();for(const r of rs){const k=blank(r[key])?'':String(r[key]);m.set(k,(m.get(k)||0)+1)}return[...m].sort((a,b)=>b[1]-a[1])}
function bars(id,key,filterId,limit=99){const g=group(filtered,key).slice(0,limit),max=g[0]?.[1]||1;$(id).innerHTML=g.length?g.map(([name,n])=>`<button class="barrow" data-value="${escapeHTML(name)}" title="Filtrar: ${escapeHTML(valueLabel(name))}"><span class="label">${escapeHTML(valueLabel(name))}</span><span class="track"><span class="fill" style="display:block;width:${n/max*100}%"></span></span><b>${nf.format(n)}</b></button>`).join(''):'<p class="empty">Nenhum resultado.</p>';$(id).querySelectorAll('button').forEach(b=>b.onclick=()=>setFilter(filterId,b.dataset.value))}
function render(){filtered=filterRows();$('resultsCount').textContent=`${nf.format(filtered.length)} de ${nf.format(records.length)} registros`;
 const scheduled=filtered.filter(r=>r.PrimDataProg).length,ups=filtered.reduce((s,r)=>s+(Number(r.qtdPlanUPS)||0),0),overdue=filtered.filter(r=>deadline(r)==='overdue').length,soon=filtered.filter(r=>deadline(r)==='soon').length;
 $('kpis').innerHTML=[['Projetos na seleção',new Set(filtered.map(r=>r.definicao_do_projeto)).size,`${nf.format(filtered.length)} registros · ${nf.format(new Set(filtered.filter(r=>!blank(r.nota)).map(r=>r.nota)).size)} notas únicas`],['UPS planejadas',ups,'Soma dos valores originais'],['Prazo DELI vencido',overdue,`Antes de ${dateLabel($('reference').value)}`],['DELI em até 15 dias',soon,`${dateLabel($('reference').value)} a ${dateLabel(addDays($('reference').value,15))}`]].map(([name,n,sub])=>`<div class="kpi"><small>${name}</small><strong>${nf.format(n)}</strong><span>${sub}</span></div>`).join('');
 bars('poloChart','Polo','fPolo');bars('companyChart','Empreiteira_Contratos','fCompany',8);bars('familyChart','Família','fFamily',8);
 const rate=filtered.length?scheduled/filtered.length:0;$('readiness').innerHTML=`<div class="bigRate">${pct(rate)}</div><div class="muted small">com data de programação</div><div class="stack"><span style="width:${rate*100}%"></span></div><div class="legend"><span><b>${nf.format(scheduled)}</b>Programados</span><span><b>${nf.format(filtered.length-scheduled)}</b>Sem programação</span></div>`;
 const months={};for(const r of filtered)if(r.PrimDataProg){const m=r.PrimDataProg.slice(0,7);months[m]=(months[m]||0)+1}const max=Math.max(1,...Object.values(months));$('timeline').innerHTML=Object.entries(months).sort().map(([m,n])=>`<div class="month"><b>${nf.format(n)}</b><div class="column" style="height:${Math.max(5,n/max*100)}px"></div><span>${m.slice(5)}/${m.slice(0,4)}</span></div>`).join('')||'<p class="empty">Sem datas de programação para esta seleção.</p>';
 renderTable();renderOwners();renderQuality();}
function renderTable(){const size=$('pageSize').value==='all'?Math.max(1,filtered.length):+$('pageSize').value,total=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(Math.max(1,page),total);let sorted=[...filtered];if(sortKey)sorted.sort((a,b)=>{const x=a[sortKey],y=b[sortKey];if(blank(x))return blank(y)?0:1;if(blank(y))return-1;return sortDir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'pt-BR',{numeric:true}))});
 $('recordsTable').innerHTML=`<thead><tr><th class="row-number" scope="col">Nº</th>${data.headers.map((h,i)=>`<th scope="col"><span class="excel-column">${colLetter(i)}</span><button data-sort="${escapeHTML(h)}">${escapeHTML(labels[h]||h)} ${h===sortKey?(sortDir===1?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${sorted.slice((page-1)*size,page*size).map((r,i)=>`<tr><td class="row-number">${(page-1)*size+i+1}</td>${data.headers.map(h=>`<td>${h==='definicao_do_projeto'?`<button class="project" data-index="${r._index}">${escapeHTML(r[h])}</button>`:h==='SttProg'?`<span class="badge ${r[h]==='Prog'?'green':''}">${escapeHTML(display(r[h],h))}</span>`:escapeHTML(display(r[h],h))}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="18" class="empty">Nenhum projeto encontrado. Ajuste os filtros.</td></tr>`}</tbody>`;
 $('tableSummary').textContent=`${nf.format(filtered.length)} obras na seleção · ${data.headers.length} colunas · ${nf.format(filtered.reduce((s,r)=>s+(Number(r.qtdPlanUPS)||0),0))} UPS planejadas. A lista acompanha os filtros automaticamente.`;
 $('pageLabel').textContent=`Página ${page} de ${total} · ${nf.format(filtered.length)} registros`;$('prev').disabled=page===1;$('next').disabled=page===total;
 $('recordsTable').querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{sortDir=sortKey===b.dataset.sort?-sortDir:1;sortKey=b.dataset.sort;renderTable()});$('recordsTable').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>showDetail(records[+b.dataset.index]));}
function showDetail(r){$('detailTitle').textContent=r.definicao_do_projeto;$('detailBody').innerHTML=data.headers.map(h=>`<dt>${escapeHTML(labels[h]||h)}</dt><dd>${escapeHTML(display(r[h],h))}</dd>`).join('');$('detail').showModal()}
function renderOwners(){const g=group(filtered,'Dono');$('ownerStats').innerHTML=`<span><b>${nf.format(filtered.filter(r=>r.Dono&&r.Dono!=='A Definir').length)}</b> com responsável definido</span><span><b>${nf.format(filtered.filter(r=>r['CÓDTEC']&&r['CÓDTEC']!=='-').length)}</b> com código definido</span>`;
 $('ownersTable').innerHTML='<thead><tr><th>Técnico / dono</th><th>Códigos técnicos</th><th>Registros</th><th>UPS planejadas</th><th>Programados</th><th>DELI vencido</th></tr></thead><tbody>'+g.map(([name,n])=>{const rs=filtered.filter(r=>(r.Dono||'')===name);return`<tr><td><button class="project" data-owner="${escapeHTML(name)}">${escapeHTML(valueLabel(name))}</button></td><td>${escapeHTML([...new Set(rs.map(r=>r['CÓDTEC']||'—'))].join(', '))}</td><td>${nf.format(n)}</td><td>${nf.format(rs.reduce((s,r)=>s+(Number(r.qtdPlanUPS)||0),0))}</td><td>${nf.format(rs.filter(r=>r.PrimDataProg).length)}</td><td>${nf.format(rs.filter(r=>deadline(r)==='overdue').length)}</td></tr>`}).join('')+'</tbody>';$('ownersTable').querySelectorAll('button').forEach(b=>b.onclick=()=>{setFilter('fOwner',b.dataset.owner);showTab('records')})}
function renderQuality(){const count=fn=>filtered.filter(fn).length,seen=new Set();let dup=0;for(const r of filtered){const key=JSON.stringify([r.definicao_do_projeto,r.nota,r.Circuito]);if(seen.has(key))dup++;seen.add(key)}
 const items=[['Sem data de programação',count(r=>!r.PrimDataProg)],['Sem Prazo DELI',count(r=>!r['Prazo DELI'])],['Dono a definir / ausente',count(r=>!r.Dono||r.Dono==='A Definir')],['Camada não definida',count(r=>!r.camada||r.camada==='Não Def. Plan.')],['Código técnico ausente / “-”',count(r=>!r['CÓDTEC']||r['CÓDTEC']==='-')],['Empreiteira ausente',count(r=>!r.Empreiteira_Contratos)],['Nota ausente',count(r=>blank(r.nota))],['UPS zeradas',count(r=>r.qtdPlanUPS===0)],['Duplicidades da chave composta',dup],['Aging divergente (vencimento)',count(r=>r['Prazo DELI']&&((r.Aging==='Vencida')!==(deadline(r)==='overdue')))],['Status × data de programação',count(r=>(r.SttProg==='Prog')!==Boolean(r.PrimDataProg))],['KPI Concluído_Elétricamente',count(r=>r['KPI Nota']==='Concluído_Elétricamente')]];
 $('quality').innerHTML=items.map(([label,n])=>`<div><strong>${nf.format(n)}</strong><span>${label}</span></div>`).join('');$('criteria').textContent=`Referência: ${dateLabel($('reference').value)}. DELI vencido = data anterior à referência; próximo = da referência até +15 dias, inclusive. Os indicadores incluem todos os KPIs; filtre KPI da nota para separar conclusões elétricas. Duplicidade = projeto + nota + circuito. Conferência restrita ao arquivo, sem validação em sistemas operacionais.`;}
function renderAuditSource(){$('auditCaption').textContent=data.imported?'Arquivo importado: conferência estrutural e indicadores recalculados. As análises textuais e fórmulas das abas importadas não são recalculadas pelo site.':'Arquivo original de 21/09/2026. Achados abaixo consideram a base completa, independentemente dos filtros.';$('auditItems').innerHTML=data.audit.map(a=>`<div class="auditItem"><span class="badge ${a.level==='Conferido'?'green':'amber'}">${escapeHTML(a.level)} · ${escapeHTML(a.sheet)}</span><h3>${escapeHTML(a.title)}</h3><p>${escapeHTML(a.detail)}</p></div>`).join('')}
function colLetter(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function renderSheets(){const s=data.sheets[+$('sheetSelect').value||0];if(!s)return;const size=30,total=Math.max(1,Math.ceil(s.rows.length/size));sheetPage=Math.max(1,Math.min(sheetPage,total));const cols=Math.max(...s.rows.map(r=>r.length),1);$('sheetMeta').textContent=`${nf.format(s.rows.length)} linhas · ${cols} colunas · ${nf.format(s.formulaCount||0)} fórmulas. Quebras e estilos são simplificados; baixe o original para a formatação completa.`;
 $('sheetTable').innerHTML=`<thead><tr><th>Linha</th>${Array.from({length:cols},(_,i)=>`<th>${colLetter(i)}</th>`).join('')}</tr></thead><tbody>${s.rows.slice((sheetPage-1)*size,sheetPage*size).map((r,i)=>{const rownum=(sheetPage-1)*size+i+1;return`<tr><td>${rownum}</td>${Array.from({length:cols},(_,j)=>{const form=s.formulas?.[colLetter(j)+rownum];return`<td ${form?`title="${escapeHTML(form)}"`:''}>${escapeHTML(blank(r[j])?'':typeof r[j]==='number'?nf.format(r[j]):dateLabel(r[j]))}${form?' <small>ƒ</small>':''}</td>`}).join('')}</tr>`}).join('')}</tbody>`;$('sheetPageLabel').textContent=`Página ${sheetPage} de ${total}`;$('sheetPrev').disabled=sheetPage===1;$('sheetNext').disabled=sheetPage===total;}
function showTab(name){activeTab=name;if(name==='records')$('records').scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===name);b.setAttribute('aria-current',b.dataset.tab===name?'page':'false')})}
function download(content,name,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function worksheet(rs){const ws=XLSX.utils.aoa_to_sheet([data.headers,...rs.map(r=>data.headers.map(h=>['PrimDataProg','Prazo DELI'].includes(h)&&r[h]?(Date.parse(r[h]+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000:r[h]))],{cellDates:true});ws['!autofilter']={ref:ws['!ref']};ws['!cols']=data.headers.map(h=>({wch:h==='definicao_do_projeto'?24:20}));for(let i=0;i<rs.length;i++)for(const h of ['PrimDataProg','Prazo DELI']){const cell=ws[XLSX.utils.encode_cell({r:i+1,c:data.headers.indexOf(h)})];if(cell&&rs[i][h])cell.z='dd/mm/yyyy'}return ws}
function exportXlsx(){try{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,worksheet(filtered),'Base Projetos');const meta=[['Arquivo de origem',data.source],['Data de referência',$('reference').value],['Quantidade de registros',filtered.length],['Busca',$('search').value],...Object.entries(mappings).filter(([id])=>$(id).value).map(([id,h])=>[h,$(id).selectedOptions[0].text]),['Filtro de prazo',$('fDeadline').value],['Campo de data',$('dateField').value],['Data inicial',$('from').value],['Data final',$('to').value]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(meta),'Critérios');XLSX.writeFile(wb,'Dono_Obra_Filtrado.xlsx');notice(`${nf.format(filtered.length)} registros exportados em Excel.`)}catch(e){notice('Não foi possível exportar: '+e.message,true)}}
function exportCsv(){const safe=v=>typeof v==='string'&&(/^[=+@\t\r]/.test(v)||/^-.+/.test(v))?"'"+v:v;const lines=[data.headers,...filtered.map(r=>data.headers.map(h=>blank(r[h])?'':h==='qtdPlanUPS'?String(r[h]).replace('.',','):safe(r[h])))].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');download('\ufeff'+lines,'Dono_Obra_Filtrado.csv','text/csv;charset=utf-8');notice(`${nf.format(filtered.length)} registros exportados em CSV (UTF-8, separador ;).`)}
function validDate(y,m,d){const dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?`${String(y).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:null}
function parseDate(v,date1904=false){if(blank(v))return null;if(v instanceof Date)return validDate(v.getUTCFullYear(),v.getUTCMonth()+1,v.getUTCDate());if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v,{date1904});return d?validDate(d.y,d.m,d.d):null}const s=String(v).trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:T.*)?$/);if(m)return validDate(+m[1],+m[2],+m[3]);m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);return m?validDate(+m[3],+m[2],+m[1]):null}
function parseNumber(v){if(typeof v==='number')return v;let s=String(v??'').trim();if(!s)return null;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return /^-?\d+(\.\d+)?$/.test(s)?Number(s):NaN}
async function importFile(file){if(!file)return;if(file.size>25*1024*1024){notice('O arquivo excede o limite de 25 MB.',true);return}notice('Lendo e conferindo o arquivo…');await new Promise(r=>setTimeout(r,20));try{let wb;if(/\.csv$/i.test(file.name)){const bytes=new Uint8Array(await file.arrayBuffer());let text=new TextDecoder('utf-8').decode(bytes);if(text.includes('\uFFFD'))text=new TextDecoder('windows-1252').decode(bytes);wb=XLSX.read(text,{type:'string',raw:true})}else wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false,cellNF:true});
 const sheets=wb.SheetNames.map(name=>{const ws=wb.Sheets[name],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true,blankrows:true}),formulas={};const origin=XLSX.utils.decode_range(ws['!ref']||'A1').s;for(const[k,c]of Object.entries(ws)){if(c&&c.f)formulas[k]='='+c.f;if(c?.z&&typeof c.v==='number'&&XLSX.SSF.is_date(c.z)){const pos=XLSX.utils.decode_cell(k),ri=pos.r-origin.r,ci=pos.c-origin.c;if(rows[ri])rows[ri][ci]=parseDate(c.v,!!wb.Workbook?.WBProps?.date1904)}}for(const row of rows)for(let i=0;i<row.length;i++)if(row[i] instanceof Date)row[i]=parseDate(row[i]);return{name,rows,formulas,formulaCount:Object.keys(formulas).length}});
 const expected=window.DONO_DATA.headers,candidates=[];for(const s of sheets){for(let i=0;i<Math.min(30,s.rows.length);i++){const names=s.rows[i].map(norm);if(names.includes(norm('definicao_do_projeto'))){candidates.push({s,i,names});break}}}let choice=candidates.find(c=>norm(c.s.name)==='base projetos')||(candidates.length===1?candidates[0]:null);if(!choice)throw Error(candidates.length?'Mais de uma base encontrada. Nomeie a aba principal como Base Projetos.':'Cabeçalho definicao_do_projeto não encontrado nas primeiras 30 linhas.');
 const missing=expected.filter(h=>!choice.names.includes(norm(h)));if(missing.length)throw Error('Colunas obrigatórias ausentes: '+missing.join(', '));if(new Set(choice.names.filter(Boolean)).size!==choice.names.filter(Boolean).length)throw Error('Há nomes de colunas duplicados no cabeçalho.');
 const indexes=expected.map(h=>choice.names.indexOf(norm(h))),rows=[],issues=[];const date1904=!!wb.Workbook?.WBProps?.date1904;
 choice.s.rows.slice(choice.i+1).forEach((r,i)=>{if(!r.some(x=>!blank(x)))return;const row=indexes.map(idx=>blank(r[idx])?null:r[idx]);if(blank(row[0]))issues.push(`linha ${choice.i+i+2}: projeto vazio`);for(const idx of [12,14]){const raw=row[idx];row[idx]=parseDate(raw,date1904);if(!blank(raw)&&!row[idx])issues.push(`linha ${choice.i+i+2}: data inválida em ${expected[idx]}`)}const raw=row[7];row[7]=parseNumber(raw);if(!blank(raw)&&!Number.isFinite(row[7]))issues.push(`linha ${choice.i+i+2}: UPS inválida`);rows.push(row)});
 if(issues.length)throw Error(`${issues.length} inconsistência(s); importação cancelada. ${issues.slice(0,5).join('; ')}`);if(!rows.length)throw Error('Nenhum registro encontrado.');
 data={source:file.name,reference:$('reference').value,updated:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),headers:expected,rows,sheets,imported:true,audit:[{sheet:choice.s.name,title:'Importação validada',level:'Conferido',detail:`${rows.length} registros e 17 campos reconhecidos. ${sheets.length} aba(s) carregada(s). Datas e UPS validadas. Nenhum registro removido por duplicidade. Fórmulas não foram recalculadas; a consulta às abas mostra os valores salvos.`}]};initialize();notice(`${nf.format(rows.length)} registros importados de ${file.name}. Uso nesta sessão. Para atualizar o site compartilhado, baixe os dados para publicar e substitua data.js no GitHub.`)}catch(e){notice('Importação não realizada. A base anterior foi mantida. '+e.message,true)}finally{$('file').value=''}}
function exportAll(){try{const wb=XLSX.utils.book_new();for(const s of data.sheets)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(s.rows),s.name.slice(0,31));XLSX.writeFile(wb,'Dono_Obra_Todas_Abas_Valores.xlsx');notice('Todas as abas exportadas com os valores salvos, sem fórmulas, gráficos ou formatação original.')}catch(e){notice(e.message,true)}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));for(const id of [...Object.keys(mappings),'fDeadline','from','to','dateField','reference'])$(id).onchange=()=>{if(!validDate(...$('reference').value.split('-').map(Number))){$('reference').value=data.reference;notice('Informe uma data de referência válida.',true)}page=1;render()};let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page=1;render()},150)};$('clear').onclick=clearFilters;$('pageSize').onchange=()=>{page=1;renderTable()};$('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('sheetSelect').onchange=()=>{sheetPage=1;renderSheets()};$('sheetPrev').onclick=()=>{sheetPage--;renderSheets()};$('sheetNext').onclick=()=>{sheetPage++;renderSheets()};$('closeDetail').onclick=()=>$('detail').close();$('detail').onclick=e=>{if(e.target===$('detail'))$('detail').close()};$('importButton').onclick=()=>$('file').click();$('file').onchange=e=>importFile(e.target.files[0]);$('exportXlsx').onclick=exportXlsx;$('exportCsv').onclick=exportCsv;$('tableExportXlsx').onclick=exportXlsx;$('tableExportCsv').onclick=exportCsv;$('exportAll').onclick=exportAll;$('publishData').onclick=()=>{download('window.DONO_DATA = '+JSON.stringify(data)+';\n','data.js','text/javascript;charset=utf-8');notice('Substitua data.js na raiz do repositório para disponibilizar esta base a todos pelo link. O arquivo Excel original continua sendo o de 21/09/2026.')};$('restore').onclick=()=>{data=structuredClone(window.DONO_DATA);initialize();notice('Base publicada restaurada nesta sessão.')};
function clock(){const now=new Date();$('clock').textContent=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now);$('today').textContent=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric'}).format(now)}
initialize();clock();setInterval(clock,1000);
